#!/bin/bash

read -p "Would you like to decode or encode? " task

while [ $task != 'encode' ]  || [ $task != 'decode'  ];
	do
		read -p "Would you like to decode or encode? " task
	if [ $task == 'encode'  ]; 
	then
		read -p "Enter the massage you would love to decode or encode " msg
		echo  $msg | base64
		break
	elif [ $task == "decode" ];
	then 
		read -p "Enter the massage you would love to decode or encode " msg
		echo $msg | base64 --decode
		break

	fi 
	done 